name: gup
services:
  main:
    type: compose
    services:
      image: ubuntu:latest
      command: tail -f /dev/null
    overrides:
      build: ./.lando/main
      environment:
        TERM: xterm-256color
    build:
      - chmod +x /app/gup.sh
      - echo "# GUP" >> ~/.bashrc
      - echo "source /app/gup.sh" >> ~/.bashrc
      - echo "source /app/gup-completion.sh" >> ~/.bashrc
tooling:
  shellcheck:
    service: main
    cmd: shellcheck -s bash *.sh
  bats:
    service: main
    cmd: bats -F tap test
