name: validation
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup BATS
        run: git clone --branch v0.4.0 https://github.com/sstephenson/bats.git
      - name: Test
        run: bats/bin/bats tests/tests.bats
